import { Bed } from "./types";

export const initialBeds: Bed[] = [
  {
    id: "bed-1",
    number: 1,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-1",
      name: "Rajesh Kumar",
      age: 54,
      gender: "Male",
      admissionDate: "2026-04-25",
      diagnosis: "Hypertension & Type 2 Diabetes",
      treatments: [
        {
          id: "t-1",
          name: "Metformin 500mg",
          type: "Medication",
          startDate: "2026-04-25",
          notes: "Twice daily after meals",
        },
        {
          id: "t-2",
          name: "Normal Saline 0.9%",
          type: "IV Drip",
          startDate: "2026-04-26",
          notes: "500ml over 4 hours",
        },
        {
          id: "t-3",
          name: "Cardiac Monitoring",
          type: "Observation",
          startDate: "2026-04-25",
          notes: "Continuous ECG monitoring",
        },
      ],
    },
  },
  {
    id: "bed-2",
    number: 2,
    ward: "General",
    status: "available",
  },
  {
    id: "bed-3",
    number: 3,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-2",
      name: "Priya Sharma",
      age: 32,
      gender: "Female",
      admissionDate: "2026-04-28",
      diagnosis: "Post-op recovery (Appendectomy)",
      treatments: [
        {
          id: "t-4",
          name: "Amoxicillin 500mg",
          type: "Medication",
          startDate: "2026-04-28",
          notes: "Thrice daily for 7 days",
        },
        {
          id: "t-5",
          name: "Wound Dressing",
          type: "Wound Care",
          startDate: "2026-04-28",
          notes: "Change every 24 hours",
        },
      ],
    },
  },
  {
    id: "bed-4",
    number: 4,
    ward: "General",
    status: "cleaning",
  },
  {
    id: "bed-5",
    number: 5,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-3",
      name: "Amit Verma",
      age: 67,
      gender: "Male",
      admissionDate: "2026-04-20",
      diagnosis: "COPD Exacerbation",
      treatments: [
        {
          id: "t-6",
          name: "Oxygen Therapy 2L/min",
          type: "Oxygen Therapy",
          startDate: "2026-04-20",
          notes: "Via nasal cannula, maintain SpO2 > 92%",
        },
        {
          id: "t-7",
          name: "Salbutamol Nebulization",
          type: "Medication",
          startDate: "2026-04-20",
          notes: "Every 6 hours",
        },
      ],
    },
  },
  {
    id: "bed-6",
    number: 6,
    ward: "General",
    status: "available",
  },
  {
    id: "bed-7",
    number: 7,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-4",
      name: "Sunita Devi",
      age: 45,
      gender: "Female",
      admissionDate: "2026-04-29",
      diagnosis: "Severe Anemia",
      treatments: [
        {
          id: "t-8",
          name: "Blood Transfusion",
          type: "IV Drip",
          startDate: "2026-04-29",
          notes: "2 units packed RBC",
        },
        {
          id: "t-9",
          name: "Iron Sucrose IV",
          type: "Medication",
          startDate: "2026-04-29",
          notes: "200mg in 100ml NS over 30 min",
        },
      ],
    },
  },
  {
    id: "bed-8",
    number: 8,
    ward: "General",
    status: "cleaning",
  },
  {
    id: "bed-9",
    number: 9,
    ward: "General",
    status: "available",
  },
  {
    id: "bed-10",
    number: 10,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-5",
      name: "Mohan Lal",
      age: 72,
      gender: "Male",
      admissionDate: "2026-04-22",
      diagnosis: "Ischemic Stroke (Recovering)",
      treatments: [
        {
          id: "t-10",
          name: "Aspirin 150mg",
          type: "Medication",
          startDate: "2026-04-22",
          notes: "Once daily",
        },
        {
          id: "t-11",
          name: "Physiotherapy",
          type: "Physiotherapy",
          startDate: "2026-04-24",
          notes: "Daily 45-min session, left-side motor rehab",
        },
      ],
    },
  },
  {
    id: "bed-11",
    number: 11,
    ward: "General",
    status: "available",
  },
  {
    id: "bed-12",
    number: 12,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-6",
      name: "Kavitha Rao",
      age: 28,
      gender: "Female",
      admissionDate: "2026-04-30",
      diagnosis: "Dengue Fever (NS1 Positive)",
      treatments: [
        {
          id: "t-12",
          name: "Platelet Monitoring",
          type: "Observation",
          startDate: "2026-04-30",
          notes: "Every 6 hours",
        },
        {
          id: "t-13",
          name: "Dextrose 5% Drip",
          type: "IV Drip",
          startDate: "2026-04-30",
          notes: "500ml over 6 hours, maintain hydration",
        },
      ],
    },
  },
  {
    id: "bed-13",
    number: 13,
    ward: "General",
    status: "cleaning",
  },
  {
    id: "bed-14",
    number: 14,
    ward: "General",
    status: "available",
  },
  {
    id: "bed-15",
    number: 15,
    ward: "General",
    status: "occupied",
    patient: {
      id: "p-7",
      name: "Deepak Singh",
      age: 41,
      gender: "Male",
      admissionDate: "2026-04-27",
      diagnosis: "Acute Pancreatitis",
      treatments: [
        {
          id: "t-14",
          name: "NPO (Nil Per Os)",
          type: "Observation",
          startDate: "2026-04-27",
          notes: "Complete bowel rest, IV nutrition",
        },
        {
          id: "t-15",
          name: "TPN (Total Parenteral Nutrition)",
          type: "IV Drip",
          startDate: "2026-04-27",
          notes: "1500 kcal/day via central line",
        },
        {
          id: "t-16",
          name: "Pre-operative Prep",
          type: "Surgery Prep",
          startDate: "2026-05-01",
          notes: "Scheduled for ERCP tomorrow morning",
        },
      ],
    },
  },
];
